import type { HeroImageSet } from "./AltHeroFrame";

/**
 * Pre-optimized AVIF + WebP variants for service-hub heroes. Each set lives in
 * `public/images/heroes/services/` and was generated by
 * `scripts/optimize-hub-heroes.mjs` from the original R2 source.
 *
 * Mobile (≤1024px) ships ~50KB AVIF at 900w; desktop ships ~70KB at 1200w. Same
 * pattern as the city hero sets, which is why location pages already score
 * ≥95 on Lighthouse. Hubs were stuck at 76-84 because they referenced
 * 500-768KB unoptimized R2 JPGs.
 */

function buildHubSet(basename: string): HeroImageSet {
  const dir = "/images/heroes/services";
  return {
    sources: [600, 900, 1200, 1920].map((w) => ({
      width: w,
      avif: `${dir}/${basename}-${w}.avif`,
      webp: `${dir}/${basename}-${w}.webp`,
    })),
    fallback: `${dir}/${basename}-1200.webp`,
  };
}

export const METAL_HUB_HERO = buildHubSet("metal-hub");
export const COMMERCIAL_HUB_HERO = buildHubSet("commercial-hub");
export const HAIL_HUB_HERO = buildHubSet("hail-hub");
// BUR hero set — formerly named tpo-hub on disk, renamed 2026-05-14 after
// confirming the files showed a gravel built-up roof close-up, not white TPO
// membrane. Available for built-up roofing pages if one is created.
export const BUR_HUB_HERO = buildHubSet("bur-hub");
// TPO_HUB_HERO removed 2026-05-14 — no genuine TPO single-ply hero exists yet.
// /tpo-roofing/ temporarily uses COMMERCIAL_HUB_HERO (Texas Med-Tech building,
// real white commercial flat roof — visually accurate for single-ply membrane).
// Restore this export when a real TPO hero asset is regenerated.
